---

- name: updating
  yum:
#    name: update
#    state: present
    update_cache: yes
- name: installing package
  import_tasks: install.yml
- name: downloading url
  get_url:
    url: "http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.24/bin/apache-tomcat-9.0.24.tar.gz"
    dest: /home/centos
    mode: "0755"