---

- name: updating
  apt:
#    name: update
#    state: present
    update_cache: yes
- name: installing package
  import_tasks: install.yml
- name: downloading url
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.8/bin/apache-tomcat-10.0.8.tar.gz"
#    dest: /usr/local
    dest: /home/ubuntu
    mode: "0755"
- name: archiving url
  ansible.builtin.unarchive:
    src: "/home/ubuntu/apache-tomcat-10.0.8.tar.gz"
    dest: /home/ubuntu
    remote_src: yes
    mode: "0755"
- name: creating a group
  group:
    name: "{{ group }}"
    state: present
- name: creating a user
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    state: present
- name: creating a directory
  file:
    path: /opt/tomcat/
    state: directory
    group: tomcat
    owner: tomcat
    mode: "0755"
- name: moving tomcat-10.0.8 to tomcat
  become_user: root
  copy:
    src: /home/ubuntu/apache-tomcat-10.0.8
    dest: /opt/tomcat/
    mode: "0755"
- name:  Reloading the systemd daemon service
  ansible.builtin.systemd:
    daemon_reload: yes
- name: starting the tomcat service
  service:
    name: tomcat
    state: started
    enabled: true
