---
- name: new file
  hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: create a file
      file:
        name: lineinfile
        path: /home/ubuntu/
        state: touch
    - name: comment a line
      lineinfile:
        state: present
        regexp: 'hi'
        line: '<!--'
