---
- name: update
  apt:
    update_cache: true
    upgrade: "dist"
    state: "latest"
- name: installing prerequisite packages
  apt:
    name: "{{ packages }}"
    state: "latest"
- name: Adding Docker repository GPG key
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/home/ubuntu"
    mode: "0755"






